---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: atomic-fruit-service-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/atomic-fruit/atomic-fruit-service
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: atomic-fruit-service-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/cvicens/atomic-fruit-service