apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: atomic-fruit-service-deploy-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  params:
    - name: APP_NAME
      default: "DUMMY"
    - name: NAMESPACE
      default: "DUMMY"
  tasks:
  - name: deploy-app
    taskRef:
      name: openshift-deploy-app
    resources:
      inputs:
      - name: app-image
        resource: app-image
    params:
      - name: APP_NAME
        value: '${params.APP_NAME}'
      - name: NAMESPACE
        value: '${params.NAMESPACE}'